package Fast_Food;


import javax.swing.JOptionPane;
import java.io.IOException;
import java.lang.IllegalStateException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.NoSuchElementException;
import java.util.Scanner;


/**
 *
 * Author: Nate Ramia
 */
public class LoginScreen extends javax.swing.JFrame {

    protected Employee[] emp = new Employee[5];
    
    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        createEmployees();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel88 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel128 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel168 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        MCJTitleDisplay = new javax.swing.JLabel();
        jlblPassword = new javax.swing.JLabel();
        jlblUsername = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jbtnExit = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnManagerLogin = new javax.swing.JButton();
        jtxtPassword = new javax.swing.JPasswordField();
        jLabel176 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel164 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(255, 51, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel8.setText("jLabel7");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 100, 120));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel9.setText("jLabel7");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 120));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel10.setText("jLabel7");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 100, 120));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel11.setText("jLabel7");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 100, 120));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel29.setText("jLabel7");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 100, 80));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel30.setText("jLabel7");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 100, 120));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel31.setText("jLabel7");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 100, 120));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel32.setText("jLabel7");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 100, 110));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel28.setText("jLabel7");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -10, 100, 120));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel33.setText("jLabel7");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, 120));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel34.setText("jLabel7");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 100, 120));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel35.setText("jLabel7");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 100, 120));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel36.setText("jLabel7");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 100, 80));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel37.setText("jLabel7");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 100, 120));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel38.setText("jLabel7");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 100, 120));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel39.setText("jLabel7");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 100, 110));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel40.setText("jLabel7");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, -10, 100, 120));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel41.setText("jLabel7");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 120));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel42.setText("jLabel7");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 100, 120));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel43.setText("jLabel7");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, 120));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel44.setText("jLabel7");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 100, 80));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel45.setText("jLabel7");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 100, 120));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel46.setText("jLabel7");
        getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 100, 120));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel47.setText("jLabel7");
        getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 100, 110));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel49.setText("jLabel7");
        getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 100, 120));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel50.setText("jLabel7");
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 100, 120));

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel51.setText("jLabel7");
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 100, 120));

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel52.setText("jLabel7");
        getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 100, 80));

        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel56.setText("jLabel7");
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 510, 100, 120));

        jLabel57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel57.setText("jLabel7");
        getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 600, 100, 120));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel64.setText("jLabel7");
        getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 100, 110));

        jLabel69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel69.setText("jLabel7");
        getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 100, 120));

        jLabel71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel71.setText("jLabel7");
        getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 100, 120));

        jLabel89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel89.setText("jLabel7");
        getContentPane().add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 100, 120));

        jLabel91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel91.setText("jLabel7");
        getContentPane().add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 100, 80));

        jLabel88.setText("jLabel7");
        getContentPane().add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 100, 120));

        jLabel93.setText("jLabel7");
        getContentPane().add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 120));

        jLabel94.setText("jLabel7");
        getContentPane().add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 100, 120));

        jLabel95.setText("jLabel7");
        getContentPane().add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 100, 120));

        jLabel96.setText("jLabel7");
        getContentPane().add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 100, 80));

        jLabel97.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel97.setText("jLabel7");
        getContentPane().add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 100, 120));

        jLabel98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel98.setText("jLabel7");
        getContentPane().add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 100, 120));

        jLabel99.setText("jLabel7");
        getContentPane().add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 100, 110));

        jLabel100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel100.setText("jLabel7");
        getContentPane().add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, -10, 100, 120));

        jLabel101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel101.setText("jLabel7");
        getContentPane().add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, 120));

        jLabel102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel102.setText("jLabel7");
        getContentPane().add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 100, 120));

        jLabel103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel103.setText("jLabel7");
        getContentPane().add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 100, 120));

        jLabel104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel104.setText("jLabel7");
        getContentPane().add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 100, 80));

        jLabel105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel105.setText("jLabel7");
        getContentPane().add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, 100, 120));

        jLabel106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel106.setText("jLabel7");
        getContentPane().add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, 100, 120));

        jLabel107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel107.setText("jLabel7");
        getContentPane().add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 100, 110));

        jLabel108.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel108.setText("jLabel7");
        getContentPane().add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 100, 120));

        jLabel109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel109.setText("jLabel7");
        getContentPane().add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 120));

        jLabel110.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel110.setText("jLabel7");
        getContentPane().add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 100, 120));

        jLabel111.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel111.setText("jLabel7");
        getContentPane().add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 100, 120));

        jLabel112.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel112.setText("jLabel7");
        getContentPane().add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 100, 80));

        jLabel113.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel113.setText("jLabel7");
        getContentPane().add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 510, 100, 120));

        jLabel114.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel114.setText("jLabel7");
        getContentPane().add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 600, 100, 120));

        jLabel115.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel115.setText("jLabel7");
        getContentPane().add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 100, 110));

        jLabel116.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel116.setText("jLabel7");
        getContentPane().add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -10, 100, 120));

        jLabel117.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel117.setText("jLabel7");
        getContentPane().add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 100, 120));

        jLabel118.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel118.setText("jLabel7");
        getContentPane().add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 100, 120));

        jLabel119.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel119.setText("jLabel7");
        getContentPane().add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 100, 120));

        jLabel120.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel120.setText("jLabel7");
        getContentPane().add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 100, 80));

        jLabel121.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel121.setText("jLabel7");
        getContentPane().add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 100, 120));

        jLabel122.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel122.setText("jLabel7");
        getContentPane().add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 600, 100, 120));

        jLabel123.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel123.setText("jLabel7");
        getContentPane().add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, 100, 110));

        jLabel124.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel124.setText("jLabel7");
        getContentPane().add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 100, 110));

        jLabel125.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel125.setText("jLabel7");
        getContentPane().add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, 100, 120));

        jLabel126.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel126.setText("jLabel7");
        getContentPane().add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 100, 120));

        jLabel128.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel128.setText("jLabel7");
        getContentPane().add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 100, 120));

        jLabel130.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel130.setText("jLabel7");
        getContentPane().add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 100, 80));

        jLabel131.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel131.setText("jLabel7");
        getContentPane().add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 100, 220));

        jLabel132.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel132.setText("jLabel7");
        getContentPane().add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, -10, 100, 120));

        jLabel133.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel133.setText("jLabel7");
        getContentPane().add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 100, 120));

        jLabel134.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel134.setText("jLabel7");
        getContentPane().add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 170, 100, 120));

        jLabel135.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel135.setText("jLabel7");
        getContentPane().add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 260, 100, 120));

        jLabel136.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel136.setText("jLabel7");
        getContentPane().add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 360, 100, 80));

        jLabel137.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel137.setText("jLabel7");
        getContentPane().add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 510, 100, 120));

        jLabel138.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel138.setText("jLabel7");
        getContentPane().add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 100, 120));

        jLabel139.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel139.setText("jLabel7");
        getContentPane().add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 430, 100, 110));

        jLabel140.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel140.setText("jLabel7");
        getContentPane().add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, -10, 100, 120));

        jLabel141.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel141.setText("jLabel7");
        getContentPane().add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 100, 120));

        jLabel142.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel142.setText("jLabel7");
        getContentPane().add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 170, 100, 120));

        jLabel143.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel143.setText("jLabel7");
        getContentPane().add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, 100, 120));

        jLabel144.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel144.setText("jLabel7");
        getContentPane().add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 360, 100, 80));

        jLabel145.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel145.setText("jLabel7");
        getContentPane().add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 510, 100, 120));

        jLabel146.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel146.setText("jLabel7");
        getContentPane().add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, 100, 120));

        jLabel147.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel147.setText("jLabel7");
        getContentPane().add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 430, 100, 110));

        jLabel148.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel148.setText("jLabel7");
        getContentPane().add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, -10, 100, 120));

        jLabel149.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel149.setText("jLabel7");
        getContentPane().add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 80, 100, 120));

        jLabel150.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel150.setText("jLabel7");
        getContentPane().add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 170, 100, 120));

        jLabel151.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel151.setText("jLabel7");
        getContentPane().add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 260, 100, 120));

        jLabel152.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel152.setText("jLabel7");
        getContentPane().add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 360, 100, 80));

        jLabel153.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel153.setText("jLabel7");
        getContentPane().add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 510, 100, 120));

        jLabel154.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel154.setText("jLabel7");
        getContentPane().add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 600, 100, 120));

        jLabel155.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel155.setText("jLabel7");
        getContentPane().add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 430, 100, 110));

        jLabel156.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel156.setText("jLabel7");
        getContentPane().add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, -10, 100, 120));

        jLabel157.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel157.setText("jLabel7");
        getContentPane().add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 80, 100, 120));

        jLabel158.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel158.setText("jLabel7");
        getContentPane().add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 170, 100, 120));

        jLabel159.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel159.setText("jLabel7");
        getContentPane().add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 260, 100, 120));

        jLabel160.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel160.setText("jLabel7");
        getContentPane().add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 360, 100, 80));

        jLabel161.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel161.setText("jLabel7");
        getContentPane().add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 510, 100, 120));

        jLabel162.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel162.setText("jLabel7");
        getContentPane().add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 600, 100, 120));

        jLabel163.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel163.setText("jLabel7");
        getContentPane().add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 430, 100, 110));

        jLabel165.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel165.setText("jLabel7");
        getContentPane().add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 100, 140));

        jLabel166.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel166.setText("jLabel7");
        getContentPane().add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 160, 100, 140));

        jLabel168.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel168.setText("jLabel7");
        getContentPane().add(jLabel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, 100, 100));

        jLabel171.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel171.setText("jLabel7");
        getContentPane().add(jLabel171, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 420, 100, 130));

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        MCJTitleDisplay.setBackground(new java.awt.Color(255, 0, 51));
        MCJTitleDisplay.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        MCJTitleDisplay.setForeground(new java.awt.Color(255, 255, 0));
        MCJTitleDisplay.setText("cJava's");

        jlblPassword.setBackground(new java.awt.Color(255, 0, 0));
        jlblPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblPassword.setForeground(new java.awt.Color(255, 255, 0));
        jlblPassword.setText("Password");

        jlblUsername.setBackground(new java.awt.Color(255, 0, 0));
        jlblUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblUsername.setForeground(new java.awt.Color(255, 255, 0));
        jlblUsername.setText("Username");

        jtxtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsernameActionPerformed(evt);
            }
        });

        jbtnExit.setBackground(new java.awt.Color(255, 0, 0));
        jbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnExit.setForeground(new java.awt.Color(255, 255, 0));
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        jbtnLogin.setBackground(new java.awt.Color(255, 0, 0));
        jbtnLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnLogin.setForeground(new java.awt.Color(255, 255, 0));
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jbtnManagerLogin.setBackground(new java.awt.Color(255, 0, 0));
        jbtnManagerLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnManagerLogin.setForeground(new java.awt.Color(255, 255, 0));
        jbtnManagerLogin.setText("Manager login");
        jbtnManagerLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnManagerLoginActionPerformed(evt);
            }
        });

        jtxtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPasswordActionPerformed(evt);
            }
        });

        jLabel176.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel176.setText("jLabel7");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Have You Done Your Code Today?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnExit)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel176, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MCJTitleDisplay)
                                .addGap(12, 12, 12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblPassword)
                                    .addComponent(jlblUsername))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jtxtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(jtxtPassword)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jbtnManagerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel176, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MCJTitleDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(73, 73, 73)
                .addComponent(jbtnManagerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 380, 710));

        jLabel67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel67.setText("jLabel7");
        getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 100, 110));

        jLabel172.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel172.setText("jLabel7");
        getContentPane().add(jLabel172, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 350, 100, 100));

        jLabel173.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel173.setText("jLabel7");
        getContentPane().add(jLabel173, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 340, 100, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, -1, -1));

        jLabel164.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel164.setText("jLabel7");
        getContentPane().add(jLabel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, -10, 100, 120));

        jLabel167.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel167.setText("jLabel7");
        getContentPane().add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 100, 220));

        jLabel174.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel174.setText("jLabel7");
        getContentPane().add(jLabel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 510, 100, 120));

        jLabel175.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fast_Food/20240403_162534 (2).jpg"))); // NOI18N
        jLabel175.setText("jLabel7");
        getContentPane().add(jLabel175, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 600, 100, 120));

        pack();
    }// </editor-fold>                        

    // Pull employee and manager data
    public void createEmployees(){
        
        try(Scanner input = new Scanner(Paths.get("employee.txt"))) {
            // read record from file
         int i = 1;
         while (input.hasNext()) { // while there is more to read
            // insert data into Employee class array                     
            emp[i] = new Employee(input.next(),
               input.next(), input.next(), Boolean.parseBoolean(input.next()), input.next());
            i++;
         }       
        } 
        catch (IOException | NoSuchElementException | 
            IllegalStateException e) {
            e.printStackTrace();
        } 
        
    }
    
    private void jtxtUsernameActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        Boolean founduser = false;
        for (int i = 1; i < emp.length; i++){
            
            if (jtxtUsername.getText().equals(emp[i].getUserName())){
                founduser = true;
                String enteredpassword = new String(jtxtPassword.getPassword());
                if (enteredpassword.equals(emp[i].getPassword())){
                    JOptionPane.showMessageDialog(null, "Login Successful");
                    
                    // Creds: Dominic Doan
                    FastFood FF = new FastFood();
                    FF.show(); // Display Fast Food ordering screen
                    
                    dispose(); // Close the Login screen
                }
                else 
                    JOptionPane.showMessageDialog(null, "Wrong password","Message",JOptionPane.ERROR_MESSAGE);
                break; // exit loop, we found user with correct password
            }
        }
        if (!founduser)
            JOptionPane.showMessageDialog(null, "Username does not exist","Message",JOptionPane.ERROR_MESSAGE);           
        
    }                                         

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void jtxtPasswordActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void jbtnManagerLoginActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(null, "Please enter Username: ", "", 
                JOptionPane.QUESTION_MESSAGE);
        String user = (input);
        
        if (user.equals(emp[1].getUserName())){
            String input1 = JOptionPane.showInputDialog(null, "Please enter Password: ", "",
                JOptionPane.QUESTION_MESSAGE);
            String pass = (input1);
            if(pass.equals(""))
                JOptionPane.showMessageDialog(this, "Please fill out password");
            else if(pass.equals(emp[1].getPassword())){
                JOptionPane.showMessageDialog(this, "Login Successful");
                
                // Creds: Dominic Doan
                ManagerMenu MGM = new ManagerMenu();
                MGM.show(); // Opens the Manager screen
                
                dispose(); // Closes the Login screen
            }
            else 
                JOptionPane.showMessageDialog(this, "Wrong password!","Message",JOptionPane.ERROR_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(this, "Access Denied");
          
        
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
  

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel MCJTitleDisplay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnManagerLogin;
    private javax.swing.JLabel jlblPassword;
    private javax.swing.JLabel jlblUsername;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration                   
}
